research:
  description: >
    Analyze the {job_type} to extract key skills, experiences, and qualifications
    required. Use the tools to gather content and identify and categorize the requirements.
  expected_output: >
    A structured list of job requirements, including necessary skills, qualifications, and experiences.

job:
  description: >
    Compile a detailed personal and professional profile to find the {job_type} oppurtunity and personal write-up for the resume .
    Utilize tools to extract and synthesize information from these sources.
  expected_output: >
    5 job oppurtunity for the job. That are suitable for skill and experience

project:
  description: >
     Analyze the {job_type} to extract what could the project for that job. Compile detailed review about the project
     and brief the insight of the project 
  expected_output: >
    An listed of most modernistic project that help to stand out the resume.

interview_pre:
  description: > 
    Create a set of potential interview questions and talking points based {job_type}.
    Utilize tools to generate relevant questions and discussion points. Make sure to use these question and talking points to
    help the candiadte highlight the main points of the resume and how it matches the job posting.
  expected_output: >
    A document containing key questions and talking points that the candidate should prepare for the initial interview.